# My Theme Configuration
theme_name: "theme1"
author: "Gary Wang"
# Header
navname: 主题名称
# favicon
favicon: /favicon.ico
# Profile
nickname: 主题昵称

### 此变量为 Markdown 格式。
description: Lorem ipsum dolor sit amet, **consectetur adipiscing elit.** <br>Fusce eget urna vitae velit *eleifend interdum at ac* nisi.
avatar: /image/avatar.jpeg

# 导航项
nav:
  目录: /archives
  分类: /category
  标签: /tag
  书签: /static/mark/index.html
  # 关于: /about
  
# 主菜单导航
## 链接关键字不应更改。
## 完整 URL 在关键字后面。
## 未使用的链接可以注释掉。
links:
  Blog: /archives
  category: /category
  Tags: /tag
  About: /about
  # FaceBook:
  # Twitter:
  # Instagram:
  # YouTube:
  # QQ:
  # Weibo:
  # WeChat:
  # Github: https://github.com/Siricee

# 链接显示方式：您有两种选择——文本或图标。
links_text_enable: false
links_icon_enable: true

# 文章页面
## 文章元信息
post_meta_enable: true

post_author_enable: true
post_date_enable: true
post_category_enable: true
## 文章版权
post_copyright_enable: true

post_copyright_author_enable: false
post_copyright_permalink_enable: false
post_copyright_license_enable: false
post_copyright_license_text: Copyright (c) 2024 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> 许可证
post_copyright_slogan_enable: false
post_copyright_slogan_text: Do you believe in <strong>DESTINY</strong>?
## 目录
post_toc_enable: true

# 页面
page_title_enable: true

# 日期/时间格式
## Hexo 使用 Moment.js 来解析和显示日期
## 您可以根据以下文档自定义日期格式：
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY年MM月D日
time_format: H:mm:ss

